const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";

const REGISTER_REQUEST = "REGISTER_REQUEST";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAILURE = "REGISTER_FAILURE";


const FORGOT_REQUEST = "FORGOT_REQUEST";
const FORGOT_SUCCESS = "FORGOT_SUCCESS";
const FORGOT_FAILURE = "FORGOT_FAILURE";

const VERIFICATION_REQUEST = "VERIFICATION_REQUEST";
const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
const VERIFICATION_FAILURE = "VERIFICATION_FAILURE";

export const types = {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,
  FORGOT_REQUEST,
  FORGOT_SUCCESS,
  FORGOT_FAILURE,
  VERIFICATION_REQUEST,
  VERIFICATION_SUCCESS,
  VERIFICATION_FAILURE
}