const GETCHAT_REQUEST = "GETCHAT_REQUEST";
const GETCHAT_SUCCESS = "GETCHAT_SUCCESS";
const GETCHAT_FAILURE = "GETCHAT_FAILURE";
const GETCONVERSATION_REQUEST = "GETCONVERSATION_REQUEST";
const GETCONVERSATION_SUCCESS = "GETCONVERSATION_SUCCESS";
const GETCONVERSATION_FAILURE = "GETCONVERSATION_FAILURE";



export const types = {
  GETCHAT_REQUEST,
  GETCHAT_SUCCESS,
  GETCHAT_FAILURE,
  GETCONVERSATION_REQUEST,
  GETCONVERSATION_SUCCESS,
  GETCONVERSATION_FAILURE
}