const GETPROFILE_REQUEST = "GETPROFILE_REQUEST";
const GETPROFILE_SUCCESS = "GETPROFILE_SUCCESS";
const GETPROFILE_FAILURE = "GETPROFILE_FAILURE";
const UPDATEPROFILE_REQUEST = "UPDATEPROFILE_REQUEST";
const UPDATEPROFILE_SUCCESS = "UPDATEPROFILE_SUCCESS";
const UPDATEPROFILE_FAILURE = "UPDATEPROFILE_FAILURE";

export const types = {
  GETPROFILE_REQUEST,
  GETPROFILE_SUCCESS,
  GETPROFILE_FAILURE,
  UPDATEPROFILE_REQUEST,
  UPDATEPROFILE_SUCCESS,
  UPDATEPROFILE_FAILURE
}