const GETPROFILE_REQUEST = "GETPROFILE_REQUEST";
const GETPROFILE_SUCCESS = "GETPROFILE_SUCCESS";
const GETPROFILE_FAILURE = "GETPROFILE_FAILURE";

export const types = {
  GETPROFILE_REQUEST,
  GETPROFILE_SUCCESS,
  GETPROFILE_FAILURE,
}